config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'tasks/index'

  get 'tasks/new'

  root 'welcome#index'
# get 'welcome/index'
  resources:tasks
  
  get '/tasks/:id/complete/:completed', to: 'tasks#complete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
     @task= Task.all 
  end

  def new
    @task = Task.new
  end
  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else 
      render 'new'
    end
  end
  
  def edit
    @task = Task.find(params[:id])

  end
  
  def update 
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path
    else 
      render 'edit'
    end
  end
  
  def show  
    @task = Task.find(params[:id])
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
    
  end
  
  def complete
    @task=Task.find(params[:id])
    @task.update_attribute(:completed, params[:completed])
    redirect_to tasks_path
  end
  
  private def task_params
    params.require(:task).permit(:title, :details,:completed)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_error_list.html.erb
<ul class = 'error list' >
    
<% @task.errors.full_messages.each do |error| %>
<%= error %>
<% end %>    
    
    
</ul>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %> <br>
<%= f.label "Title" %> <br>
<%= f.text_field :title %> <br>
<%= f.label "Detail" %> <br>
<%= f.text_area :details %> <br>
<% if request.path.include?("edit") %> 
    <%= f.label "Completed?" %>
    <%= f.check_box :completed  %> <br>
<% end %>
<%= f.submit %> <br>


<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'error_list' %>
<%= render 'form'%>
<p></p><%= button_to "Tasks", tasks_index_path, :method => :get %></p>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ul>
<% @task.each do |task|  %>
<li> 
    <strong>
        <%= link_to task.title, task_path(task) %>
    </strong>
    
    <%= link_to(check_box_tag(:task, :completed, task.completed) , 
        "/tasks/#{task.id}/complete/#{!task.completed}")%>


</li>
<% end %>
</ul>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>


<%= render 'error_list' %>
<%= render 'form'%>
<p></p><%= button_to "Tasks", tasks_index_path, :method => :get %></p>

app/views/tasks/show.html.erb
    <p> <em><%= @task.details %> </em></p>
    <p>Completed?<%=  link_to(check_box_tag(:task, :completed, @task.completed) , 
        "/tasks/#{@task.id}/complete/#{!@task.completed}")%></p>
    <p></p><%= link_to 'Edit Task', edit_task_path(@task) %></p>
    <%= link_to 'Delete', task_path(@task), method: :delete %>
    <%= button_to "Tasks", tasks_index_path, :method => :get %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>My To Do List</h1>




<%= link_to 'look at your tasks', tasks_path %>